### ISSUE TITLE
This issue is regarding VGG face2 dataset please share working link to download it, as mentioned meta/identity_meta.csv file is not available, apart from that for the given hyperparameter values, there is lot deviation in results from reported as per paper.

### ISSUE THREAD

**Issue by AKANKSHASINGH233** [meghdadk/SCRUB#2]

**Comment by meghdadk** [comment]
Hi @AKANKSHASINGH233 
We downloaded VGG face2 from https://github.com/ox-vgg/vgg_face2 and created the lacuna dataset as described in the paper, using the [create_lacuna](https://github.com/meghdadk/SCRUB/blob/main/create_lacuna.py). 
It seems that the download links are not available anymore. Unfortunately, we are not allowed to redistribute the data. I would suggest you contact them to see if there is any way to download the dataset. 
w.r.t the hyperparameters, please note that each experiment requires careful tuning of the parameters. Scrub, particularly is sensitive to batch size and the number of epochs (both max and min). Hope this helps.
