### ISSUE TITLE
Wrong Implementation of EU/CF

### ISSUE THREAD

**Issue by shash42** [meghdadk/SCRUB#3]
The implementation of EU/CF updates the 'first K' layers of the network instead of the 'final K' as proposed originally in the associated [paper](https://arxiv.org/abs/2201.06640). Moreover, the numbers reported are for the weakest version, where only the final layer is unlearnt.

We request the authors to fix this, or mention the mistake explicitly on the repository to prevent further misreporting of our work.

**Comment by meghdadk** [comment]
Dear @shash42 
We ask that you double-check. e.g., you could print the model architectures (resnet and allcnn) and see the layers we use. You will see then that we unlearn the final (top-k) layers. Additionally,  in both CF and EU, we unlearn more than one single layer, ensuring no misrepresentation of your work.
PS: please feel free to send a pull request including your implementation of your CF and EU. Best

**Comment by shash42** [comment]
Apologies. This was based on the Appendix description in the associated paper: "In both ‘EU-k’ and ‘CF-k’ baselines, for
both ResNet and All-CNN we freeze all the layers except for the last block of the network."

Closing the issue if the correct interpretation has been ensured in the code.
